server:
  port: 8088
spring:
  thymeleaf:
    suffix: .html
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cheeper?createDatabaseIfNotExist=true
    username: root
    password: cheeper

url:
  bucket: https://cheeper.s3.amazonaws.com/

aws:
  s3:
    access-key: ${ACCESS_KEY}
    secret-key: ${SECRET_KEY}
    region: ${REGION}
