server:
  port: 8088
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    suffix: .html
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cheeper?createDatabaseIfNotExist=true
    username: root
    password: cheeper
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER_EMAIL}
    password: ${USER_PASSWORD}
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

url:
  bucket: https://cheeper.s3.amazonaws.com/
email:
  code:
    sender: ${USER_EMAIL}

aws:
  s3:
    access-key: ${ACCESS_KEY}
    secret-key: ${SECRET_KEY}
    region: ${REGION}
